#################################################################################
# MIT License                                                                   #
#                                                                               #
# Copyright (c) 2024 Chris Yang                                                 #
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in all#
# copies or substantial portions of the Software.                               #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE #
# SOFTWARE.                                                                     #
#################################################################################

############# parent chart values: !!! override values of sub-chart !!! #############

# simple-rest-crud-service is an independent service in this project, NOT depends on any other serivce, 
# but this helm chart is structured with multi-microserves for the future project
# so just deploy this service ONLY, set 'initContainers.enabled=false' or it should setup as 'true'
simple-rest-crud-service:
  enabled: true
  k8s:
    servicemonitor: false
    hpa: false
  image: 
    repository: 336371013214.dkr.ecr.us-east-1.amazonaws.com/simple-rest-crud-service
    tag: 1.0.0-SNAPSHOT
    pullPolicy: Always
  sidecar: 
    enabled: true
    value: 
      - image: 336371013214.dkr.ecr.us-east-1.amazonaws.com/mariadb:11
        name: sidecar-db
        lifecycle:
          ????????
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MARIADB_DATABASE
          value: "crud-api"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1000m
      memory: 128Mi
    requests:
      cpu: 1000m
      memory: 128Mi
  initContainers:
    enabled: false
  configmap:
    data: 
      APP_SERVER_PORT: "8080"
      APP_MANAGEMENT_PORT: "8081"
      DB_URL: "jdbc:mariadb://localhost:3306/crud-api"
      DATABASE_DRIVER: "org.mariadb.jdbc.Driver"
      DB_INIT: |
        #!/bin/bash
        mysql -uroot -ppassword -h127.0.0.1 -e "DROP USER IF EXISTS chris"
        mysql -uroot -ppassword -h127.0.0.1 -e "SELECT user FROM mysql.user"
        mysql -uroot -ppassword -h127.0.0.1 -e "CREATE OR REPLACE USER chris@'%' IDENTIFIED BY 'chris2024'"
        mysql -uroot -ppassword -h127.0.0.1 -e "GRANT ALL PRIVILEGES ON * . * TO 'chris'@'%'"
  secret:
    stringData:
      DB_USER: "chris"
      DB_PASSWORD: "chris2024!"


############# parent chart values: k8s resources, status of serviceAccount
# global.serviceAccount.enabled = k8s.serviceaccount
k8s:
  serviceaccount: true

############# parent chart values: global values used by sub-chart
# serviceAccount.name = global.serviceAccount.name
global:
  deploy:
    env: chris-env
  serviceAccount:
    enabled: true
    name: jenkins-cicd-test-service

############# parent chart values: service account def
# global.serviceAccount.name = serviceAccount.name
serviceAccount:
  annotations: {}
  name: jenkins-cicd-test-service