#################################################################################
# MIT License                                                                   #
#                                                                               #
# Copyright (c) 2024 Chris Yang                                                 #
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in all#
# copies or substantial portions of the Software.                               #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE #
# SOFTWARE.                                                                     #
#################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
  namespace: chris-service-portfolio
  labels:
    run: test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-pod
  template:
    metadata:
      labels:
        run: test-pod
      name: test-pod
    spec:
      # securityContext: 
      #   runAsUser: 1010
      #   runAsGroup: 1010
      containers:
      - image: amazonlinux:2
        name: test-pod
        command: ["sh", "-c"]
        args: 
        - |
          yum udpate -y
          yum install -y free java-17 awscli less mysql wget bind-utils nc iputils unzip zip tar
          sleep infinity
        env: 
        - name: TEST
          value: "all good!"
        readinessProbe:
          exec:
            command: ["ls", "/opt"]
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - image: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/mariadb:11
        name: sidecar-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MARIADB_DATABASE
          value: "crud-api"
        - name: db-init.sh
          value: |
            #!/bin/bash
            mysql -uroot -ppassword -h127.0.0.1 -e "DROP USER IF EXISTS chris"
            mysql -uroot -ppassword -h127.0.0.1 -e "SELECT user FROM mysql.user"
            mysql -uroot -ppassword -h127.0.0.1 -e "CREATE OR REPLACE USER chris@'%' IDENTIFIED BY 'chris2024'"
            mysql -uroot -ppassword -h127.0.0.1 -e "GRANT ALL PRIVILEGES ON * . * TO 'chris'@'%'"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"