#################################################################################
# MIT License                                                                   #
#                                                                               #
# Copyright (c) 2024 Chris Yang                                                 #
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in all#
# copies or substantial portions of the Software.                               #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE #
# SOFTWARE.                                                                     #
#################################################################################
---
- name: build and push image to ecr
  hosts: localhost
  tasks:
  - name: build app image
    community.docker.docker_image:
      build:
        path: /opt/chris-service/Jenkins-CICD-Test-Service/SimpleRestCrudService
      name: simple-rest-crud-service
      tag: 1.0.0-SNAPHOST
      push: false
      source: build

  - name: aws ecr login
    ansible.builtin.shell: |
      /usr/bin/aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com

  - name: tag the image
    ansible.builtin.command: /usr/bin/docker tag simple-rest-crud-service:1.0.0-SNAPHOST <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/simple-rest-crud-service:1.0.0-SNAPHOST

  - name: push to ecr
    ansible.builtin.command: /usr/bin/docker push <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/simple-rest-crud-service:1.0.0-SNAPHOST

- name: build values.yaml template
  ??

- name: build helm chart
  host: localhost
  tasks: 
  - name: build helm chart
    ansible.builtin.command: helm package ./K8sHelmChart --version=1.0.0
    args:
      chdir: /opt/chris-service/Jenkins-CICD-Test-Service

  - name: aws ecr login
    ansible.builtin.shell: |
      /usr/bin/aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com

  - name: push helm chart to ecr
    ansible.builtin.command: helm push jenkins-cicd-test-service-chart-1.0.0.tgz oci://<aws-account-id>.dkr.ecr.us-east-1.amazonaws.com
    args:
     chdir: /opt/chris-service/Jenkins-CICD-Test-Service


- name: deploy helm chart to eks
  host: eks
  tasks: 
  - name: deploy to eks
    ansible.builtin.command: helm install batch-rule-engine oci://<aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/jenkins-cicd-test-service-chart --version 1.0.0 --namespace chris-service-portfolio --atomic --timeout 300s --debug
    ignore_errors: true

  - name: upgrade to eks
    ansible.builtin.command: helm upgrade batch-rule-engine oci://<aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/jenkins-cicd-test-service-chart --version 1.0.0 --namespace chris-service-portfolio --atomic --timeout 300s --debug
    ignore_errors: true