# yaml: https://eksctl.io/usage/schema/#
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: chris-eks
  region: us-east-1
  tags: 
   env: dev/test
   account: chris-free
vpc:
  id: "vpc-0abd1bb7d1a1a20dc"
  subnets:
    public:
      us-east-1b:
          id: "subnet-007bf72041d7ab626"
      us-east-1a:
          id: "subnet-0e7f1a11e9ba646a6"
nodeGroups:
  - name: test-ng
    instanceType: m3.large
    desiredCapacity: 2
