# yaml: https://eksctl.io/usage/schema/#
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: chris-eks
  region: us-east-1
  tags: 
   env: dev/test
   account: chris-free
vpc:
  id: "..."
  subnets:
    public:
      us-east-1b:
          id: "..."
      us-east-1a:
          id: "..."
nodeGroups:
  - name: test-ng
    instanceType: m3.large
    desiredCapacity: 2
