version: "3.8"
services:
  db:
    image: "mariadb:11"
    container_name: "chris-db"
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - chris-network

  auth-entry:
    image: "auth-entry-service:${IMAGE_TAG}"
    container_name: "chris-db"
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - chris-network

...will add more

networks:
  chris-network:
    driver: bridge

volumes:
  db-volume:
  cache-volume:

