#################################################################################
# MIT License                                                                   #
#                                                                               #
# Copyright (c) 2024 Chris Yang                                                 #
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in all#
# copies or substantial portions of the Software.                               #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE #
# SOFTWARE.                                                                     #
#################################################################################

############# subchart values: k8s resources
k8s:
  deployment: true
  service: true
  configmap: true
  secret: true
  hpa: false

############# subchart values: deploy env 
deploy:
  env: chris-env

############# subchart values: auto scaling
replicaCount: 1
hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 80


############# subchart values: service def
# server port is service-advertise-port
# management port is health-check and metrics-check 
service:
  type: ClusterIP
  server: 
    port: 8080
  management:
    port: 8081
  healthcheck: 
    exists: true
    path: /health
    readinessProbe: 
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5

############# subchart values: image def
image:
  repository: 336371013214.dkr.ecr.us-east-1.amazonaws.com/cicd-test-app
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always
  
# pull image from private repo with secret
imagePullSecrets: []

# full name override
fullnameOverride: ""

############# subchart values: pod resource
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

############# subchart values: pod anno in spec
podAnnotations: {}

############# subchart values: pod privileges
podSecurityContext: {}
  # fsGroup: 2000
  # runAsUser: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

############# subchart values: pod allocation
nodeSelector: {}
tolerations: []
affinity: {}

############# subchart values: init container
initContainers:
  enabled: false
  definition:
  - name: <dep service name>
    image: radial/busyboxplus:curl
    command: 
    - sh
    - -c
    args:
    - "until curl http://<service>.chris-service-portfolio.svc.cluster.local:8081/health; do echo waiting for <service-name>...; sleep 5; done"

############# subchart values: pod env
envFrom:
  exist: true

############# subchart values: configmap def
configmap:
    data: 
      APP_SERVER_PORT: "8080"
      APP_MANAGEMENT_PORT: "8081"
      DB_URL: "jdbc:mariadb://localhost:3306/crud-api"
      DATABASE_DRIVER: "org.mariadb.jdbc.Driver"

############# subchart values: secret def
secret:
    stringData:
      DB_USER: "chris"
      DB_PASSWORD: "chris2024!"
