INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES ('Neil','Hamilton','neil@chrismember.ca')
INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES ('Dominic','Buckland','dominic@chrismember.ca')
INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES ('Lily','Stewart','stewart@chrismember.ca')
INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES ('Dan','Burgess','burgess@chrismember.ca')
INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES  ('Trevor','Coleman','coleman@chrismember.ca')
INSERT INTO `member` (`first_name`,`last_name`,`email`) VALUES  ('William','Glover','glover@chrismember.ca')